//v26 © 2011 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TCL=="undefined"){(function(){var ca=function(){var h=document,s=h.body,q=h.documentElement,T=eval("/*@cc_on!@*/false"),J=function(a,c){for(var b="",g=0;g<c;g++)b+=a;return b},w=J("a",50),u=(Tynt.e||"")+"ic.tynt.com",U=(Tynt.e||"")+"de.tynt.com/deb/?id="+w,B=function(a){return a.replace(/^\s+|\s+$/g,"")},o,C;if(window.addEventListener){o=function(a,c,b){a.addEventListener(c,b,false)};C=function(a,c,b){a.removeEventListener(c,b,false)}}else{o=function(a,c,b){a.attachEvent("on"+c,b)};
C=function(a,c,b){a.detachEvent("on"+c,b)}}var V=function(a,c){var b=location.hostname.split("."),g=2;do{var j=b.slice(b.length-g,b.length).join(".");h.cookie=a+";path=/;domain=."+j+";"+c;g++}while(h.cookie.indexOf(a)==-1&&g<=b.length);if(h.cookie.indexOf(a)==-1)h.cookie=a+";path=/;"+c},K=function(a){h.readyState=="complete"?a():o(window,"load",function(){setTimeout(function(){if(typeof h.readyState=="undefined"&&!T)h.readyState="complete";a()},10)})},m=function(a,c){var b=[],g=function(j,e){var d=
"http://"+j.replace("id="+w,"id="+Tynt.join("~"));if(d.indexOf(u+"/b/p?")>-1&&typeof Tynt.b=="string")d+="&b="+Tynt.b;var i=new Image(1,1);if(e)i.onerror=e;i.src=d};m=function(j,e){b.push([j,e])};K(function(){m=g;for(var j=0;j<b.length;j++)m(b[j][0],b[j][1]);b=null});m(a,c)},L=function(a){var c=[],b="",g;for(g in a)if(a.hasOwnProperty(g)){c.push(b,g,"=",a[g]);b="&"}return c.join("")},N=function(a){for(var c=0,b=a.length<100?a.length:100,g=0;g<b;g++)c+=a.charCodeAt(g);a=Math.floor(Math.random()*3844);
b=Math.abs((new Date).getTime()-12281184E5);return M(b,7)+M((c+a)%3844,2)},O=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var c=Math.floor(a/62);a=a-c*62;return c>=62?O(c)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(c)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},M=function(a,c){var b=O(a);return J("0",
c-b.length)+b},P=B((h.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),W=function(){for(var a=h.getElementsByTagName("link"),c=0;c<a.length;c++)if(a[c].getAttribute("rel")&&a[c].getAttribute("rel").match("canonical")&&a[c].getAttribute("href")){a=a[c].getAttribute("href");c=location.protocol+"//"+location.host+location.pathname;var b=h.getElementsByTagName("base")[0];if(b)if(b=b.getAttribute("href"))c=b;if(!a.match(/^http/)){if(a.charAt(0)=="/"){b=c.indexOf("/",9);if(b>
-1)c=c.slice(0,b)}else{b=c.lastIndexOf("/");if(b>9)c=c.slice(0,b+1);else c+="/"}a=c+a}return a}return""},Q=function(a){return a.replace(/^https?:\/\//,"")},X=function(a,c){for(var b=c+"=",g=a.split(";"),j=0;j<g.length;j++){for(var e=g[j];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(b)==0)return e.substring(b.length,e.length)}return null},Y=function(){var a=X(h.cookie,"tracertraffic"),c=encodeURIComponent(Q(W())),b=h.location.hash;b=/tynt=/.test(b)?b.match(/tynt=?([^?&$#]*)/)[1]:false;
var g=u+"/b/p?id="+w+(a?"&et="+a:"")+(b?"&a="+b:"")+"&ts="+(new Date).getTime(),j=g+(c?"&cu="+c:""),e=j+(h.referrer?"&r="+encodeURIComponent(Q(h.referrer)):"");a=e+"&t="+encodeURIComponent(P);m(a,function(){m(e,function(){m(j,function(){m(g)})})})},D=function(){var a=[];return function(c){for(var b=a.length-1;b>=0;b--)if(a[b]==c)return false;a.unshift(c);a.length>3&&a.pop();return true}},Z=D(),$=D(),aa=function(){var a,c=function(){window.removeEventListener("blur",c,false);E(a);return true};return function(b){a=
b.target||b.srcElement;window.removeEventListener("blur",c,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",c,false);setTimeout(function(){h.removeEventListener("blur",c,false)},1E4)}return true}}(),R=function(a){E(a.target||a.srcElement,true)},x,S=function(a){a=a.target||a.srcElement;x=a.nodeName=="IMG"?a:null},F=function(){var a=function(d){return typeof d.pageX=="number"?{x:d.pageX-(q.scrollLeft?q.scrollLeft:s.scrollLeft),y:d.pageY-(q.scrollTop?q.scrollTop:
s.scrollTop)}:{x:d.clientX,y:d.clientY}},c=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=s.clientWidth||d.y>=s.clientHeight},b=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=q.clientWidth||d.y>=q.clientHeight},g=function(d){return d.target.nodeName=="#document"},j=function(d){d=a(d);return d.x<=4||d.y<=4||d.x>=q.clientWidth-4||d.y>=q.clientHeight-4},e=function(d){e=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?c:b:navigator.userAgent.match("Firefox")?g:j;e(d)};
return function(d){if(x&&e(d)){E(x);x=null}return true}}(),ba=function(){function a(f,k){if(n(f))m(u+"/b/o?id="+w+(k?"&i=":"&l=")+encodeURIComponent(f)+"&ts="+(new Date).getTime())}function c(f){var k=f.target||f.srcElement;if(f.button<2)for(;k&&k!=h;){f=k.href;if(k.nodeName=="A"&&f&&location.href.split("#")[0]!=f.split("#")[0]&&!/^javascript/i.test(f)){a(f);break}k=k.parentNode}}function b(){i&&a(i,true)}function g(f){if(f){f=f.target||f.srcElement;i=f.src||f.data||"flash";o(window,"blur",b)}}function j(){i=
null;C(window,"blur",b)}function e(f){o(f,"mouseover",g);o(f,"mouseout",j)}function d(){i&&a(i,true)}var i,n=D();o(document,"mousedown",c);K(function(){for(var f=h.getElementsByTagName("iframe"),k=f.length-1;k>=0;k--){var p=f[k];if(p.src)e(p);else if(p.name)try{o(frames[p.name].document,"mousedown",c)}catch(r){}}f=h.getElementsByTagName("object");for(k=f.length-1;k>=0;k--)e(f[k])});o(window,"beforeunload",d);o(window,"unload",d)},G;if(Tynt.c)G=function(){};else{Tynt.c=true;G=function(){var a=true,
c,b=function(g,j){var e=w,d;d=(d=B(j))?d.split(/\s+/i).length:0;var i={id:e,wc:d,c:j,f:a?1:0,t:P},n;for(n in g)if(g.hasOwnProperty(n))i[n]=g[n];a=false;n=i.trace_type;delete i.trace_type;e=i.g;delete i.g;d=[];for(var f=["id","wc","f","w","h","t","c"],k=0;k<f.length;k++){var p=f[k],r=i[p];r&&d.push([p,encodeURIComponent(r).replace(/\'/g,"%27")]);delete i[p]}for(var l in i)if(i.hasOwnProperty(l))(f=i[l])&&d.push([l,encodeURIComponent(f).replace(/\'/g,"%27")]);l=[];k=2048-(("http://"+u+"/a/t/x#?").length+
(3+e.length)+5);p=d.length;var v=r=0,t=0,H,y,I,z,A=0;for(l[A]={g:e,tp:null};r<p&&l.length<35;){H=d[r][0];i=d[r][1];I=H.length+2;y=k-I-v;if(y>0){f=i.substring(t,t+y);z=f.slice(-2).indexOf("%");if(z>-1){f=i.substring(t,t+y-2+z);v+=z+2}v+=f.length+I;t+=f.length;l[A][H]=f}else v=k;if(v>=k){l[++A]={g:e,p:A};v=0}if(t>=i.length){r++;t=0}}l[0].tp=l.length;m(u+"/b/t/"+n+"?"+L(l[0]));for(e=1;e<l.length;e++)m(u+"/b/x/"+n+"?"+L(l[e]))};/tynt=nout/.test(location.href)||ba();if(window.addEventListener){navigator.userAgent.match("Firefox/2")||
s.addEventListener("copy",R,false);window.addEventListener("mousedown",S,false);window.addEventListener("dragleave",F,false);window.addEventListener("dragexit",F,false);h.addEventListener("contextmenu",aa,false)}else{s.attachEvent("oncopy",R);h.getElementsByTagName("html")[0].attachEvent("ondragleave",F);s.attachEvent("onmousedown",S)}if(h.cookie.indexOf("tracertraffic=")!=-1)if(!h.referrer||h.referrer.indexOf(location.host)==-1)V("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");Y();m(U);
return function(g,j){if(!h.getElementById("tyntSS")){var e;if(j)e=typeof getSelection!="undefined"?getSelection().toString():h.selection.createRange().text;var d=g.src;d&&!e&&$(d)&&b({g:N(d),trace_type:3,w:g.width,h:g.height},d);if(e&&B(e).length&&g.nodeName!="TEXTAREA"&&g.nodeName!="INPUT"){d=Z(e);var i={trace_type:1};if(d)c=N(e);i.g=c;var n=Tynt.m?Tynt.m(i,e):true;d&&n&&b(i,e)}}}}}var E=G()};Tynt.TCL=function(){document.body?ca():setTimeout(Tynt.TCL,300)}})();Tynt.TCL()};
